-- 授予 OB_SHARE 访问 remap 依赖目标的权限
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

GRANT SELECT ON OB_DW.F_ORDER_METRIC TO OB_SHARE;
GRANT SELECT ON OB_ODS.CUST_DIM TO OB_SHARE;
GRANT SELECT ON OB_STAGE.REGION_DIM TO OB_SHARE;
