-- OB_BASE 授予跨 schema 依赖对象所需权限
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER SESSION SET CURRENT_SCHEMA = OB_BASE;
GRANT EXECUTE ON OB_BASE.T_AUDIT_TAG TO OB_APP;
GRANT SELECT ON OB_BASE.CORE_ACCOUNT TO OB_ANALYTICS;
GRANT SELECT ON OB_BASE.CORE_ACCOUNT TO OB_APP;
