-- OB_FIN 授予跨 schema 依赖对象所需权限
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER SESSION SET CURRENT_SCHEMA = OB_FIN;
GRANT EXECUTE ON OB_FIN.FN_GET_BALANCE TO OB_APP;
GRANT EXECUTE ON OB_FIN.FN_GET_BALANCE TO OB_UTIL;
GRANT SELECT ON OB_FIN.FIN_LEDGER TO OB_APP;
GRANT SELECT ON OB_FIN.SEQ_LEDGER TO OB_APP;
