-- OB_SALES 授予跨 schema 依赖对象所需权限
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER SESSION SET CURRENT_SCHEMA = OB_SALES;
GRANT SELECT ON OB_SALES.APP_ORDER TO OB_ANALYTICS;
GRANT SELECT ON OB_SALES.APP_ORDER TO OB_APP;
GRANT SELECT ON OB_SALES.APP_ORDER_LINE TO OB_APP;
GRANT SELECT ON OB_SALES.SEQ_ORDER TO OB_APP;
GRANT SELECT ON OB_SALES.SEQ_ORDER_LINE TO OB_APP;
