-- Hydra Matrix scenario (OceanBase side)
-- Creates destination schemas with deliberate omissions/extra objects.
-- V2: Corrected schema/object names to align with remap_rules_hydra.txt and added idempotency.
SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE;

PROMPT === Dropping existing target schemas (if they exist) ===

BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_MASTER CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_APP CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_DW CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_ANALYTICS CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_SUPPLY CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_STREAM CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_REF CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_STAGE CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_SHARE CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_AUDIT CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_BILL CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_FIN CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_SEC CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_ML CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP USER OB_ODS CASCADE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF;
END;
/


PROMPT === Creating target schemas ===

CREATE USER OB_MASTER IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO OB_MASTER;

CREATE USER OB_APP IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE PACKAGE TO OB_APP;

CREATE USER OB_DW IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE, CREATE TRIGGER TO OB_DW;

CREATE USER OB_ANALYTICS IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE VIEW TO OB_ANALYTICS;

CREATE USER OB_SUPPLY IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE, CREATE TRIGGER, CREATE SEQUENCE, CREATE PROCEDURE, CREATE VIEW TO OB_SUPPLY;

CREATE USER OB_STREAM IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE TO OB_STREAM;

CREATE USER OB_REF IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO OB_REF;

CREATE USER OB_STAGE IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO OB_STAGE;

CREATE USER OB_SHARE IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE SYNONYM, CREATE PROCEDURE, CREATE FUNCTION TO OB_SHARE;

CREATE USER OB_AUDIT IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE TO OB_AUDIT;

CREATE USER OB_BILL IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO OB_BILL;

CREATE USER OB_FIN IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE VIEW, CREATE PROCEDURE, CREATE PACKAGE, CREATE TYPE TO OB_FIN;

CREATE USER OB_SEC IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE TO OB_SEC;

CREATE USER OB_ML IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO OB_ML;

CREATE USER OB_ODS IDENTIFIED BY ob_pass;
GRANT CREATE SESSION, CREATE TABLE TO OB_ODS;


PROMPT === OB_REF/OB_STAGE lookup layer (partial) ===

-- ORA_REF.REGION_DIM -> OB_REF.REGION_DIM
CREATE TABLE OB_REF.REGION_DIM (
    REGION_ID    NUMBER(6) PRIMARY KEY,
    REGION_CODE  VARCHAR2(20) NOT NULL,
    REGION_NAME  VARCHAR2(80) NOT NULL
    -- ACTIVE_FLAG / CREATED_AT removed
);
-- SEQ_REGION is intentionally missing to be detected

-- ORA_REF.CHANNEL_DIM -> OB_STAGE.CHANNEL_DIM
CREATE TABLE OB_STAGE.CHANNEL_DIM (
    CHANNEL_ID   NUMBER(6) PRIMARY KEY,
    CHANNEL_CODE VARCHAR2(12),
    CHANNEL_NAME VARCHAR2(40),
    REGION_ID    NUMBER(6),
    MIGRATION_TAG VARCHAR2(10), -- Extra column
    OMS_OBJECT_NUMBER NUMBER,   -- 需忽略的 OMS 系统列
    OMS_RELATIVE_FNO  NUMBER,   -- 需忽略的 OMS 系统列
    OMS_BLOCK_NUMBER  NUMBER,   -- 需忽略的 OMS 系统列
    OMS_ROW_NUMBER    NUMBER,   -- 需忽略的 OMS 系统列
    OMS_EXTRA_FLAG    VARCHAR2(10), -- 非忽略 OMS 列，期望被报告为目标端多余
    OMS_AUDIT_NOTE    VARCHAR2(30)  -- 非忽略 OMS 列，期望被报告为目标端多余
    -- ONLINE_FLAG and FK omitted
);

-- ORA_REF.SERVICE_LEVEL -> OB_STAGE.SERVICE_LEVEL (missing)
-- ORA_REF.SHIP_METHOD -> OB_STAGE.SHIP_METHOD (missing)

-- Sequences for channel/service/ship_method intentionally missing

-- ORA_REF.SP_REFRESH_LOOKUP -> OB_SHARE.SP_REFRESH_LOOKUP (missing)


PROMPT === OB_MASTER/OB_ODS/OB_APP domains (with gaps) ===

-- ORA_CORE.CUSTOMER_DIM -> OB_MASTER.CUSTOMER_DIM
CREATE TABLE OB_MASTER.CUSTOMER_DIM (
    CUSTOMER_ID   NUMBER(12) PRIMARY KEY,
    CUSTOMER_CODE VARCHAR2(20),
    REGION_ID     NUMBER(6)
    -- VIP_FLAG, LOYALTY_SCORE, etc. omitted. No FK.
);

-- ORA_CORE.ADDRESS_DIM -> OB_ODS.ADDRESS_DIM (missing)

-- ORA_CORE.SEQ_CUSTOMER -> OB_MASTER.SEQ_CUSTOMER
CREATE SEQUENCE OB_MASTER.SEQ_CUSTOMER START WITH 100 INCREMENT BY 1;

-- ORA_CORE.SP_PROFILE_REFRESH -> OB_APP.SP_PROFILE_REFRESH (missing)

-- ORA_CORE.PKG_CUSTOMER_API -> OB_APP.PKG_CUSTOMER_API (spec only)
CREATE OR REPLACE PACKAGE OB_APP.PKG_CUSTOMER_API AS
    PROCEDURE GET_DETAILS(p_cust_id NUMBER);
END;
/


PROMPT === OB_DW/OB_APP/OB_ANALYTICS order domain (with gaps) ===

-- ORA_ORD.ORDER_FACT -> OB_DW.F_ORDER
CREATE TABLE OB_DW.F_ORDER (
    ORDER_ID    NUMBER(12) PRIMARY KEY,
    REGION_ID   NUMBER(6),
    STATUS      VARCHAR2(1),
    ORDER_TOTAL NUMBER(12,2)
);

-- ORA_ORD.ORDER_LINE -> OB_DW.F_ORDER_LINE
CREATE TABLE OB_DW.F_ORDER_LINE (
    ORDER_LINE_ID NUMBER(12) PRIMARY KEY,
    ORDER_ID      NUMBER(12),
    CATEGORY_ID   NUMBER(6),
    QUANTITY      NUMBER(6)
    -- UNIT_PRICE/DISCOUNT omitted
);

-- ORA_ORD.SEQ_ORDER -> OB_APP.SEQ_ORDER_FLOW
CREATE SEQUENCE OB_APP.SEQ_ORDER_FLOW START WITH 10000 INCREMENT BY 5;

-- ORA_ORD.TRG_ORDER_FACT_BI -> OB_DW.TRG_F_ORDER_BI (missing)
-- ORA_ORD.SP_REPRICE_LINE -> OB_APP.SP_REPRICE_LINE (missing)
-- ORA_ORD.FN_ORDER_MARGIN -> OB_APP.FN_ORDER_MARGIN (missing)

-- ORA_ORD.PKG_ORDER_WORKFLOW -> OB_APP.PKG_ORDER_WORKFLOW (spec only)
CREATE OR REPLACE PACKAGE OB_APP.PKG_ORDER_WORKFLOW AS
    PROCEDURE ADVANCE_ORDER(p_order_id NUMBER);
END;
/
-- Package body intentionally missing

-- ORA_ORD.VW_OPEN_ORDERS -> OB_ANALYTICS.VW_OPEN_ORDERS (missing)

CREATE TABLE OB_DW.EXTRA_FACT_GHOST (
    GHOST_ID NUMBER PRIMARY KEY,
    INFO     VARCHAR2(50)
);

CREATE SEQUENCE OB_DW.EXTRA_LOAD_SEQ START WITH 1;


PROMPT === OB_SUPPLY/OB_STREAM fulfillment layer ===

-- ORA_FULFILL.SHIPMENT_FACT -> OB_SUPPLY.SHIPMENT_FACT
CREATE TABLE OB_SUPPLY.SHIPMENT_FACT (
    SHIPMENT_ID NUMBER(12) PRIMARY KEY,
    ORDER_ID    NUMBER(12),
    SHIP_DATE   DATE
    -- other columns removed
);

-- ORA_FULFILL.SHIPMENT_EVENT -> OB_STREAM.SHIPMENT_EVENT (missing)
-- ORA_FULFILL.SEQ_SHIPMENT -> OB_SUPPLY.SEQ_SHIPMENT (missing)
-- ORA_FULFILL.TRG_SHIPMENT_FACT_BI -> OB_SUPPLY.TRG_SHIPMENT_FACT_BI (missing)
-- ORA_FULFILL.SP_CLOSE_SHIPMENT -> OB_SUPPLY.SP_CLOSE_SHIPMENT (missing)
-- ORA_FULFILL.VW_DUE_SHIPMENTS -> OB_ANALYTICS.VW_DUE_SHIPMENTS (missing)


PROMPT === OB_ANALYTICS layer ===

-- ORA_ANALYTICS.VW_CUSTOMER_SPEND -> OB_ANALYTICS.VW_CUSTOMER_SPEND
CREATE OR REPLACE VIEW OB_ANALYTICS.VW_CUSTOMER_SPEND AS
SELECT c.CUSTOMER_ID, SUM(f.ORDER_TOTAL) AS TOTAL
  FROM OB_MASTER.CUSTOMER_DIM c
  JOIN OB_DW.F_ORDER f ON c.REGION_ID = f.REGION_ID -- Logical join, may not be correct but tests syntax
 GROUP BY c.CUSTOMER_ID;

-- ORA_ANALYTICS.VW_REGION_PERF -> OB_ANALYTICS.VW_REGION_PERF (missing)
-- ORA_ANALYTICS.VW_DELIVERY_DELAY -> OB_ANALYTICS.VW_DELIVERY_DELAY (missing)
-- ORA_ANALYTICS.SP_SNAPSHOT_FACTS -> OB_ANALYTICS.SP_SNAPSHOT_FACTS (missing)


PROMPT === OB_AUDIT / OB_BILL / OB_FIN layers (mostly missing) ===

-- ORA_AUDIT objects all missing to test detection
CREATE TABLE OB_AUDIT.EXTRA_EVENT_STUB (
    STUB_ID NUMBER,
    MSG VARCHAR2(100)
);

-- ORA_BILL.INVOICE_HEADER -> OB_BILL.INVOICE_HEADER
CREATE TABLE OB_BILL.INVOICE_HEADER (
    INVOICE_ID    NUMBER(12) PRIMARY KEY,
    ORDER_ID      NUMBER(12)
    -- All other columns removed
);
-- INVOICE_LINE, SEQ_INVOICE, TRIGGER, VIEW are all missing.

-- ORA_BILL.SP_POST_INVOICE -> OB_FIN.SP_POST_INVOICE (missing)
-- ORA_BILL.PKG_BILLING_ENGINE -> OB_FIN.PKG_BILLING_ENGINE (missing)


PROMPT === OB_SEC security layer (partial) ===

-- ORA_SEC.USER_MATRIX -> OB_SEC.USER_MATRIX
CREATE TABLE OB_SEC.USER_MATRIX (
    USER_ID    NUMBER(10) PRIMARY KEY,
    LOGIN_NAME VARCHAR2(40),
    ROLE_CODE  VARCHAR2(20)
    -- LAST_ORDER_ID/ACTIVE_FLAG removed, no FK
);
-- ROLE_RIGHTS table, sequence, procedures, and view omitted.


PROMPT === OB_SHARE integration helpers (partial) ===

-- ORA_UTIL.SYN_CUSTOMER -> OB_SHARE.SYN_CUSTOMER (missing)
-- ORA_UTIL.SYN_ORDER -> OB_SHARE.SYN_ORDER (missing)
-- ORA_UTIL.SYN_INVOICE -> OB_SHARE.SYN_INVOICE (missing)

-- ORA_UTIL.SYN_REGION -> OB_SHARE.SYN_REGION
CREATE SYNONYM OB_SHARE.SYN_REGION FOR OB_REF.REGION_DIM;

-- ORA_UTIL.FN_CANARY -> OB_SHARE.FN_CANARY
CREATE OR REPLACE FUNCTION OB_SHARE.FN_CANARY RETURN VARCHAR2 AS
BEGIN
    RETURN 'OB_CANARY_OK';
END;
/
-- PKG_DATA_ROUTER is missing


PROMPT === OB_ML machine learning (partial) ===

-- ORA_ML.MODEL_VERSION -> OB_ML.MODEL_VERSION
CREATE TABLE OB_ML.MODEL_VERSION (
    MODEL_ID   NUMBER(8) PRIMARY KEY,
    VERSION_NO VARCHAR2(10)
    -- STATUS/OWNER/CREATED_AT removed
);
-- MODEL_FEATURE table, sequence, proc/function, view all missing.

CREATE TABLE OB_STAGE.EXTRA_LOOKUP_SHADOW (
    SHADOW_ID NUMBER,
    DATA VARCHAR2(50)
);


PROMPT === OceanBase target setup complete ===
