-- Hydra Matrix target-side DDL (OceanBase Oracle-compatible tenant)
-- Run inside the tenant that will host the remapped objects.  This script purposely
-- leaves gaps, wrong column sets, and extra artifacts so that the comparator surfaces
-- missing/mismatched objects across every type.
SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE;

PROMPT === Creating target schemas / users ===

CREATE USER OB_MASTER IDENTIFIED BY ob_master_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_MASTER;

CREATE USER OB_APP IDENTIFIED BY ob_app_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_APP;

CREATE USER OB_DW IDENTIFIED BY ob_dw_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_DW;

CREATE USER OB_ANALYTICS IDENTIFIED BY ob_analytics_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_ANALYTICS;

CREATE USER OB_SUPPLY IDENTIFIED BY ob_supply_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_SUPPLY;

CREATE USER OB_STREAM IDENTIFIED BY ob_stream_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_STREAM;

CREATE USER OB_REF IDENTIFIED BY ob_ref_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_REF;

CREATE USER OB_STAGE IDENTIFIED BY ob_stage_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_STAGE;

CREATE USER OB_SHARE IDENTIFIED BY ob_share_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_SHARE;

CREATE USER OB_AUDIT IDENTIFIED BY ob_audit_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_AUDIT;

CREATE USER OB_BILL IDENTIFIED BY ob_bill_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_BILL;

CREATE USER OB_FIN IDENTIFIED BY ob_fin_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_FIN;

CREATE USER OB_SEC IDENTIFIED BY ob_sec_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_SEC;

CREATE USER OB_ML IDENTIFIED BY ob_ml_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_ML;

CREATE USER OB_ODS IDENTIFIED BY ob_ods_pass;
GRANT CONNECT, RESOURCE, DBA TO OB_ODS;

PROMPT === OB_REF / OB_STAGE lookup landing (incomplete on purpose) ===

CREATE TABLE OB_REF.REGION_DIM (
    REGION_ID     NUMBER(6) PRIMARY KEY,
    REGION_CODE   VARCHAR2(20) NOT NULL,
    REGION_NAME   VARCHAR2(80) NOT NULL,  -- should be 120 after migration
    CREATED_AT    DATE DEFAULT SYSDATE,
    MIGRATED_NOTE VARCHAR2(60)
);
-- ACTIVE_FLAG and the unique constraint on REGION_CODE are missing intentionally.
-- OB_REF.SEQ_REGION is intentionally not created, forcing a missing-sequence finding.

CREATE TABLE OB_STAGE.CHANNEL_DIM (
    CHANNEL_ID    NUMBER(6) PRIMARY KEY,
    CHANNEL_CODE  VARCHAR2(12) NOT NULL,
    CHANNEL_NAME  VARCHAR2(50) NOT NULL,
    REGION_ID     NUMBER(6),
    MIGRATION_TAG VARCHAR2(10)
);
-- ONLINE_FLAG column and FK to REGION_DIM are omitted intentionally.

CREATE TABLE OB_STAGE.SERVICE_LEVEL (
    SERVICE_LEVEL_ID NUMBER(6) PRIMARY KEY,
    SERVICE_CODE     VARCHAR2(10) NOT NULL,
    TARGET_DAYS      NUMBER(3)
);
-- DESCRIPTION column and the unique constraint are missing.

-- OB_STAGE.SHIP_METHOD table + sequence are intentionally not created.

CREATE SEQUENCE OB_STAGE.SEQ_CHANNEL START WITH 200 INCREMENT BY 2;
-- SEQ_SERVICE and SEQ_SHIP_METHOD are omitted to trigger missing-sequence warnings.

CREATE TABLE OB_STAGE.EXTRA_LOOKUP_SHADOW (
    ID NUMBER PRIMARY KEY,
    NOTE VARCHAR2(40)
);
-- Extra table to ensure the comparator reports "extra object" noise on the target side.

PROMPT === OB_MASTER / OB_ODS landing for core customer data ===

CREATE TABLE OB_MASTER.CUSTOMER_DIM (
    CUSTOMER_ID     NUMBER(10) PRIMARY KEY,
    CUSTOMER_CODE   VARCHAR2(30) NOT NULL,
    CUSTOMER_NAME   VARCHAR2(120) NOT NULL, -- should have been 180
    EMAIL           VARCHAR2(180),          -- should have been 270 per 1.5× rule
    STATUS          VARCHAR2(1)  DEFAULT 'A',
    REGION_ID       NUMBER(6)    NOT NULL,
    CREATED_AT      DATE DEFAULT SYSDATE,
    UPDATED_AT      DATE,
    MIGRATED_NOTE   VARCHAR2(200)
);
-- VIP_FLAG, LOYALTY_SCORE, and PREFERRED_CHANNEL_ID are missing; FK constraints omitted.

CREATE SEQUENCE OB_MASTER.SEQ_CUSTOMER START WITH 2000 INCREMENT BY 1;

CREATE TABLE OB_ODS.ADDRESS_DIM (
    ADDRESS_ID    NUMBER(12) PRIMARY KEY,
    CUSTOMER_ID   NUMBER(10) NOT NULL,
    LINE1         VARCHAR2(160) NOT NULL,
    LINE2         VARCHAR2(160),
    CITY          VARCHAR2(60)  NOT NULL,
    POSTAL_CODE   VARCHAR2(20),
    LOAD_SOURCE   VARCHAR2(10)
);
-- ADDRESS_TYPE, COUNTRY_CODE, and ACTIVE_FLAG columns are missing; FK not recreated.

PROMPT === OB_APP partial program units ===

CREATE SEQUENCE OB_APP.SEQ_ORDER_FLOW START WITH 99000 INCREMENT BY 5;

CREATE OR REPLACE PROCEDURE OB_APP.SP_REPRICE_LINE (
    p_line_id   IN NUMBER,
    p_new_price IN NUMBER
) AS
BEGIN
    NULL;
END;
/

CREATE OR REPLACE PACKAGE OB_APP.PKG_CUSTOMER_API AS
    PROCEDURE SET_STATUS(p_customer_id NUMBER, p_status VARCHAR2);
END PKG_CUSTOMER_API;
/
-- Package body intentionally missing.

CREATE OR REPLACE PACKAGE OB_APP.PKG_ORDER_WORKFLOW AS
    PROCEDURE ADVANCE_STATUS(p_order_id NUMBER, p_status VARCHAR2);
END PKG_ORDER_WORKFLOW;
/
-- Package body missing, so both CANCEL_ORDER procedure and body coverage will be reported.

-- OB_APP.SP_PROFILE_REFRESH and OB_APP.FN_ORDER_MARGIN are intentionally absent.

PROMPT === OB_DW fact layer with extra noise ===

CREATE TABLE OB_DW.F_ORDER (
    ORDER_ID     NUMBER(12),
    ORDER_CODE   VARCHAR2(40), -- should have been 60
    CUSTOMER_ID  NUMBER(10),
    STATUS       VARCHAR2(1),
    ORDER_TOTAL  NUMBER(14,2),
    CREATED_AT   DATE
);
-- REGION_ID, CHANNEL_ID, SERVICE_LEVEL_ID, ORDER_MARGIN, NOTES columns plus PK/constraints are missing.

CREATE TABLE OB_DW.F_ORDER_LINE (
    ORDER_LINE_ID NUMBER(12),
    ORDER_ID      NUMBER(12),
    PRODUCT_CODE  VARCHAR2(40),
    QUANTITY      NUMBER(10,2)
);
-- Unique constraint on (ORDER_ID, LINE_NUM) and DISCOUNT_RATE column are missing.

CREATE SEQUENCE OB_DW.EXTRA_LOAD_SEQ START WITH 1 INCREMENT BY 1;
-- No trigger or sequence tied to ORDER FACT objects; TRG_F_ORDER_BI is missing entirely.

CREATE TABLE OB_DW.EXTRA_FACT_GHOST (
    ID NUMBER PRIMARY KEY,
    NOTE VARCHAR2(60)
);
-- Extra table exists only on the OceanBase side.

PROMPT === OB_SUPPLY / OB_STREAM logistics layer ===

CREATE TABLE OB_SUPPLY.SHIPMENT_FACT (
    SHIPMENT_ID  NUMBER(12) PRIMARY KEY,
    ORDER_ID     NUMBER(12) NOT NULL,
    STATUS       VARCHAR2(1) DEFAULT 'N',
    SHIP_DATE    DATE
);
-- SERVICE_LEVEL_ID and DELIVERY_DATE columns are missing, as are the sequence/trigger/procedure.

CREATE TABLE OB_STREAM.SHIPMENT_EVENT (
    EVENT_ID     NUMBER(12) PRIMARY KEY,
    SHIPMENT_ID  NUMBER(12) NOT NULL,
    EVENT_CODE   VARCHAR2(20) NOT NULL,
    CREATED_AT   DATE DEFAULT SYSDATE
);
-- NOTES column intentionally left out.

-- OB_SUPPLY.SEQ_SHIPMENT, OB_SUPPLY.TRG_SHIPMENT_FACT_BI, OB_SUPPLY.SP_CLOSE_SHIPMENT, and OB_ANALYTICS.VW_DUE_SHIPMENTS are not created.

PROMPT === OB_ANALYTICS reporting layer (partial) ===

CREATE OR REPLACE VIEW OB_ANALYTICS.VW_CUSTOMER_SPEND AS
SELECT c.CUSTOMER_NAME,
       SUM(o.ORDER_TOTAL) AS TOTAL_SPEND
  FROM OB_MASTER.CUSTOMER_DIM c
  LEFT JOIN OB_DW.F_ORDER o ON o.CUSTOMER_ID = c.CUSTOMER_ID
 GROUP BY c.CUSTOMER_NAME;

CREATE OR REPLACE VIEW OB_ANALYTICS.VW_REGION_PERF AS
SELECT r.REGION_NAME,
       COUNT(o.ORDER_ID) AS ORDER_COUNT
  FROM OB_REF.REGION_DIM r
  LEFT JOIN OB_DW.F_ORDER o ON 1 = 0
 GROUP BY r.REGION_NAME;
-- REGION_ID column is missing from OB_DW.F_ORDER, so the join condition degenerates to 1=0.

-- VW_OPEN_ORDERS, VW_DELIVERY_DELAY, VW_DUE_SHIPMENTS, VW_FEATURE_COVERAGE, and SP_SNAPSHOT_FACTS are intentionally missing.

PROMPT === OB_AUDIT audit landing (missing core pieces) ===

CREATE TABLE OB_AUDIT.AUDIT_LOG (
    AUDIT_ID    NUMBER(12),
    SOURCE_SCHEMA VARCHAR2(30),
    OBJECT_NAME VARCHAR2(64),
    OPERATION   VARCHAR2(20),
    STATUS      VARCHAR2(1),
    CREATED_AT  DATE
);
-- Table exists but lacks PK/sequence/trigger; JOB_RUN table is not created at all.

CREATE TABLE OB_AUDIT.EXTRA_EVENT_STUB (
    ID NUMBER PRIMARY KEY,
    NOTE VARCHAR2(40)
);

-- Sequences, trigger, procedure, and function for the audit schema are omitted.

PROMPT === OB_BILL / OB_FIN finance layer ===

CREATE TABLE OB_BILL.INVOICE_HEADER (
    INVOICE_ID    NUMBER(12) PRIMARY KEY,
    ORDER_ID      NUMBER(12),
    STATUS        VARCHAR2(1),
    INVOICE_TOTAL NUMBER(14,2)
);
-- CUSTOMER_ID, DUE_DATE, PAID_DATE, COMMENTS columns are missing.

-- OB_BILL.INVOICE_LINE table is missing entirely; SEQ_INVOICE exists but trigger does not.
CREATE SEQUENCE OB_BILL.SEQ_INVOICE START WITH 500 INCREMENT BY 1;

-- OB_FIN.SP_POST_INVOICE, OB_FIN.PKG_BILLING_ENGINE BODY, and OB_FIN.VW_OVERDUE_INVOICE are intentionally not deployed.
CREATE OR REPLACE PACKAGE OB_FIN.PKG_BILLING_ENGINE AS
    PROCEDURE ALLOCATE_REVENUE(p_invoice_id NUMBER);
END PKG_BILLING_ENGINE;
/

PROMPT === OB_SEC security layer with truncated coverage ===

CREATE TABLE OB_SEC.USER_MATRIX (
    USER_ID    NUMBER(10) PRIMARY KEY,
    USERNAME   VARCHAR2(60) NOT NULL,
    STATUS     VARCHAR2(1)  DEFAULT 'A',
    LAST_LOGIN DATE,
    SUSPEND_REASON VARCHAR2(200)
);
-- Missing CUSTOMER_ID column and unique constraint on USERNAME.

-- ROLE_RIGHTS table is absent.

CREATE SEQUENCE OB_SEC.SEQ_USER START WITH 75000 INCREMENT BY 2;

CREATE OR REPLACE PROCEDURE OB_SEC.SP_GRANT_ROLE (
    p_user_id IN NUMBER,
    p_role    IN VARCHAR2
) AS
BEGIN
    NULL;
END;
/
-- FN_IS_AUTHORIZED and VW_ACTIVE_USERS are intentionally missing.

PROMPT === OB_SHARE integration layer ===

CREATE SYNONYM OB_SHARE.SYN_REGION FOR OB_STAGE.REGION_DIM;
CREATE OR REPLACE FUNCTION OB_SHARE.FN_CANARY RETURN VARCHAR2 IS
BEGIN
    RETURN 'OB';
END;
/
-- SYN_CUSTOMER, SYN_ORDER, SYN_INVOICE, PKG_DATA_ROUTER, and SP_REFRESH_LOOKUP are not deployed.

PROMPT === OB_ML machine learning layer ===

CREATE TABLE OB_ML.MODEL_VERSION (
    MODEL_ID      NUMBER(12) PRIMARY KEY,
    MODEL_NAME    VARCHAR2(60) NOT NULL,
    VERSION_LABEL VARCHAR2(30) NOT NULL,
    TRAINED_AT    DATE
);
-- STATUS column is missing.

CREATE TABLE OB_ML.MODEL_FEATURE (
    FEATURE_ID   NUMBER(12) PRIMARY KEY,
    MODEL_ID     NUMBER(12) NOT NULL,
    FEATURE_NAME VARCHAR2(60)
);
-- DATA_TYPE, IMPORTANCE columns and FK constraint are missing.

CREATE SEQUENCE OB_ML.SEQ_MODEL START WITH 10 INCREMENT BY 1;

CREATE OR REPLACE FUNCTION OB_ML.FN_SCORE_MODEL (
    p_model_id IN NUMBER
) RETURN NUMBER IS
BEGIN
    RETURN p_model_id;
END;
/
-- SP_REGISTER_MODEL and VW_FEATURE_COVERAGE are missing.

PROMPT === Hydra Matrix OceanBase target definition complete ===
COMMIT;
