-- Hydra Matrix source-side DDL (Oracle)
-- Creates ten source schemas feeding fifteen OceanBase targets via remap rules.
SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE;

PROMPT === Creating source schemas ===

CREATE USER ORA_CORE IDENTIFIED BY ora_core_pass DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO ORA_CORE;

CREATE USER ORA_ORD IDENTIFIED BY ora_ord_pass DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO ORA_ORD;

CREATE USER ORA_FULFILL IDENTIFIED BY ora_fulfill_pass DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO ORA_FULFILL;

CREATE USER ORA_REF IDENTIFIED BY ora_ref_pass DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO ORA_REF;

CREATE USER ORA_ANALYTICS IDENTIFIED BY ora_analytics_pass DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE VIEW, CREATE PROCEDURE TO ORA_ANALYTICS;

CREATE USER ORA_AUDIT IDENTIFIED BY ora_audit_pass DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO ORA_AUDIT;

CREATE USER ORA_BILL IDENTIFIED BY ora_bill_pass DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO ORA_BILL;

CREATE USER ORA_SEC IDENTIFIED BY ora_sec_pass DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO ORA_SEC;

CREATE USER ORA_UTIL IDENTIFIED BY ora_util_pass DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE VIEW, CREATE SYNONYM, CREATE PROCEDURE TO ORA_UTIL;

CREATE USER ORA_ML IDENTIFIED BY ora_ml_pass DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO ORA_ML;

PROMPT === ORA_REF lookup layer ===

CREATE TABLE ORA_REF.REGION_DIM (
    REGION_ID      NUMBER(6)     CONSTRAINT PK_REGION_DIM PRIMARY KEY,
    REGION_CODE    VARCHAR2(20)  NOT NULL,
    REGION_NAME    VARCHAR2(120) NOT NULL,
    ACTIVE_FLAG    VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CREATED_AT     DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_REGION_DIM_CODE UNIQUE (REGION_CODE)
);

CREATE TABLE ORA_REF.CHANNEL_DIM (
    CHANNEL_ID     NUMBER(6)     CONSTRAINT PK_CHANNEL_DIM PRIMARY KEY,
    CHANNEL_CODE   VARCHAR2(12)  NOT NULL,
    CHANNEL_NAME   VARCHAR2(60)  NOT NULL,
    ONLINE_FLAG    VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    REGION_ID      NUMBER(6)     NOT NULL,
    CONSTRAINT UK_CHANNEL_DIM_CODE UNIQUE (CHANNEL_CODE),
    CONSTRAINT FK_CHANNEL_DIM_REGION FOREIGN KEY (REGION_ID)
        REFERENCES ORA_REF.REGION_DIM(REGION_ID)
);

CREATE TABLE ORA_REF.SERVICE_LEVEL (
    SERVICE_LEVEL_ID   NUMBER(6)    CONSTRAINT PK_SERVICE_LEVEL PRIMARY KEY,
    SERVICE_CODE       VARCHAR2(10) NOT NULL,
    DESCRIPTION        VARCHAR2(120),
    TARGET_DAYS        NUMBER(3)    DEFAULT 2,
    CONSTRAINT UK_SERVICE_CODE UNIQUE (SERVICE_CODE)
);

CREATE TABLE ORA_REF.SHIP_METHOD (
    SHIP_METHOD_ID     NUMBER(6)    CONSTRAINT PK_SHIP_METHOD PRIMARY KEY,
    SHIP_METHOD_CODE   VARCHAR2(16) NOT NULL,
    SERVICE_LEVEL_ID   NUMBER(6)    NOT NULL,
    CHANNEL_ID         NUMBER(6)    NOT NULL,
    ACTIVE_FLAG        VARCHAR2(1)  DEFAULT 'Y',
    CREATED_AT         DATE         DEFAULT SYSDATE,
    CONSTRAINT UK_SHIP_METHOD_CODE UNIQUE (SHIP_METHOD_CODE),
    CONSTRAINT FK_SHIP_METHOD_SERVICE FOREIGN KEY (SERVICE_LEVEL_ID)
        REFERENCES ORA_REF.SERVICE_LEVEL(SERVICE_LEVEL_ID),
    CONSTRAINT FK_SHIP_METHOD_CHANNEL FOREIGN KEY (CHANNEL_ID)
        REFERENCES ORA_REF.CHANNEL_DIM(CHANNEL_ID)
);

CREATE INDEX ORA_REF.IDX_CHANNEL_DIM_REGION ON ORA_REF.CHANNEL_DIM(REGION_ID);
CREATE INDEX ORA_REF.IDX_SHIP_METHOD_CHANNEL ON ORA_REF.SHIP_METHOD(CHANNEL_ID);

CREATE SEQUENCE ORA_REF.SEQ_REGION    START WITH 1 INCREMENT BY 1 CACHE 50;
CREATE SEQUENCE ORA_REF.SEQ_CHANNEL   START WITH 100 INCREMENT BY 1 CACHE 50;
CREATE SEQUENCE ORA_REF.SEQ_SERVICE   START WITH 10 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ORA_REF.SEQ_SHIP_METHOD START WITH 500 INCREMENT BY 5;

CREATE OR REPLACE PROCEDURE ORA_REF.SP_REFRESH_LOOKUP AS
BEGIN
    NULL; -- placeholder to ensure procedure existence for remap validation
END;
/

PROMPT === ORA_CORE customer domain ===

CREATE TABLE ORA_CORE.CUSTOMER_DIM (
    CUSTOMER_ID          NUMBER(10)                            CONSTRAINT PK_CUSTOMER_DIM PRIMARY KEY,
    CUSTOMER_CODE        VARCHAR2(30)  NOT NULL,
    CUSTOMER_NAME        VARCHAR2(120) NOT NULL,
    EMAIL                VARCHAR2(180),
    STATUS               VARCHAR2(1)   DEFAULT 'A' NOT NULL,
    VIP_FLAG             VARCHAR2(1)   DEFAULT 'N',
    REGION_ID            NUMBER(6)     NOT NULL,
    PREFERRED_CHANNEL_ID NUMBER(6),
    LOYALTY_SCORE        NUMBER(5,2)   DEFAULT 0,
    CREATED_AT           DATE          DEFAULT SYSDATE NOT NULL,
    UPDATED_AT           DATE,
    CONSTRAINT UK_CUSTOMER_CODE UNIQUE (CUSTOMER_CODE),
    CONSTRAINT FK_CUSTOMER_REGION FOREIGN KEY (REGION_ID)
        REFERENCES ORA_REF.REGION_DIM(REGION_ID),
    CONSTRAINT FK_CUSTOMER_CHANNEL FOREIGN KEY (PREFERRED_CHANNEL_ID)
        REFERENCES ORA_REF.CHANNEL_DIM(CHANNEL_ID)
);

CREATE TABLE ORA_CORE.ADDRESS_DIM (
    ADDRESS_ID      NUMBER(12)   CONSTRAINT PK_ADDRESS_DIM PRIMARY KEY,
    CUSTOMER_ID     NUMBER(10)   NOT NULL,
    ADDRESS_TYPE    VARCHAR2(20) NOT NULL,
    LINE1           VARCHAR2(200) NOT NULL,
    LINE2           VARCHAR2(200),
    CITY            VARCHAR2(80)  NOT NULL,
    POSTAL_CODE     VARCHAR2(20)  NOT NULL,
    COUNTRY_CODE    VARCHAR2(5)   NOT NULL,
    ACTIVE_FLAG     VARCHAR2(1)   DEFAULT 'Y',
    CONSTRAINT FK_ADDRESS_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES ORA_CORE.CUSTOMER_DIM(CUSTOMER_ID)
);

CREATE INDEX ORA_CORE.IDX_CUSTOMER_REGION ON ORA_CORE.CUSTOMER_DIM(REGION_ID, PREFERRED_CHANNEL_ID);
CREATE INDEX ORA_CORE.IDX_ADDRESS_CUSTOMER ON ORA_CORE.ADDRESS_DIM(CUSTOMER_ID);

CREATE SEQUENCE ORA_CORE.SEQ_CUSTOMER START WITH 1000 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE PROCEDURE ORA_CORE.SP_PROFILE_REFRESH(
    p_customer_id IN NUMBER
) AS
BEGIN
    UPDATE ORA_CORE.CUSTOMER_DIM
       SET UPDATED_AT = SYSDATE
     WHERE CUSTOMER_ID = p_customer_id;
END;
/

CREATE OR REPLACE PACKAGE ORA_CORE.PKG_CUSTOMER_API AS
    PROCEDURE SET_STATUS(p_customer_id NUMBER, p_status VARCHAR2);
    FUNCTION GET_SCORE(p_customer_id NUMBER) RETURN NUMBER;
END PKG_CUSTOMER_API;
/

CREATE OR REPLACE PACKAGE BODY ORA_CORE.PKG_CUSTOMER_API AS
    PROCEDURE SET_STATUS(p_customer_id NUMBER, p_status VARCHAR2) IS
    BEGIN
        UPDATE ORA_CORE.CUSTOMER_DIM
           SET STATUS = p_status,
               UPDATED_AT = SYSDATE
         WHERE CUSTOMER_ID = p_customer_id;
    END;

    FUNCTION GET_SCORE(p_customer_id NUMBER) RETURN NUMBER IS
        v_score NUMBER;
    BEGIN
        SELECT NVL(LOYALTY_SCORE, 0)
          INTO v_score
          FROM ORA_CORE.CUSTOMER_DIM
         WHERE CUSTOMER_ID = p_customer_id;
        RETURN v_score;
    END;
END PKG_CUSTOMER_API;
/

PROMPT === ORA_ORD ordering domain ===

CREATE TABLE ORA_ORD.ORDER_FACT (
    ORDER_ID          NUMBER(12)   CONSTRAINT PK_ORDER_FACT PRIMARY KEY,
    ORDER_CODE        VARCHAR2(40) NOT NULL,
    CUSTOMER_ID       NUMBER(10)   NOT NULL,
    REGION_ID         NUMBER(6)    NOT NULL,
    CHANNEL_ID        NUMBER(6)    NOT NULL,
    SERVICE_LEVEL_ID  NUMBER(6),
    STATUS            VARCHAR2(1)  DEFAULT 'N' NOT NULL,
    ORDER_TOTAL       NUMBER(14,2),
    ORDER_MARGIN      NUMBER(12,2),
    NOTES             VARCHAR2(400),
    CREATED_AT        DATE         DEFAULT SYSDATE,
    UPDATED_AT        DATE,
    CONSTRAINT UK_ORDER_FACT_CODE UNIQUE (ORDER_CODE),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES ORA_CORE.CUSTOMER_DIM(CUSTOMER_ID),
    CONSTRAINT FK_ORDER_REGION FOREIGN KEY (REGION_ID)
        REFERENCES ORA_REF.REGION_DIM(REGION_ID),
    CONSTRAINT FK_ORDER_CHANNEL FOREIGN KEY (CHANNEL_ID)
        REFERENCES ORA_REF.CHANNEL_DIM(CHANNEL_ID),
    CONSTRAINT FK_ORDER_SERVICE FOREIGN KEY (SERVICE_LEVEL_ID)
        REFERENCES ORA_REF.SERVICE_LEVEL(SERVICE_LEVEL_ID)
);

CREATE TABLE ORA_ORD.ORDER_LINE (
    ORDER_LINE_ID   NUMBER(12)    CONSTRAINT PK_ORDER_LINE PRIMARY KEY,
    ORDER_ID        NUMBER(12)    NOT NULL,
    LINE_NUM        NUMBER(4)     NOT NULL,
    PRODUCT_CODE    VARCHAR2(40)  NOT NULL,
    QUANTITY        NUMBER(10,2)  NOT NULL,
    UNIT_PRICE      NUMBER(12,2)  NOT NULL,
    DISCOUNT_RATE   NUMBER(5,2)   DEFAULT 0,
    CONSTRAINT UK_ORDER_LINE UNIQUE (ORDER_ID, LINE_NUM),
    CONSTRAINT FK_ORDER_LINE_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES ORA_ORD.ORDER_FACT(ORDER_ID)
);

CREATE INDEX ORA_ORD.IDX_ORDER_FACT_CUST ON ORA_ORD.ORDER_FACT(CUSTOMER_ID, CREATED_AT);
CREATE INDEX ORA_ORD.IDX_ORDER_LINE_ORDER ON ORA_ORD.ORDER_LINE(ORDER_ID);

CREATE SEQUENCE ORA_ORD.SEQ_ORDER START WITH 50000 INCREMENT BY 10;

CREATE OR REPLACE TRIGGER ORA_ORD.TRG_ORDER_FACT_BI
BEFORE INSERT ON ORA_ORD.ORDER_FACT
FOR EACH ROW
BEGIN
    IF :NEW.ORDER_ID IS NULL THEN
        SELECT ORA_ORD.SEQ_ORDER.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL;
    END IF;
    IF :NEW.ORDER_CODE IS NULL THEN
        :NEW.ORDER_CODE := 'OO-' || TO_CHAR(ORA_ORD.SEQ_ORDER.CURRVAL);
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE ORA_ORD.SP_REPRICE_LINE (
    p_order_line_id IN NUMBER,
    p_new_price     IN NUMBER
) AS
BEGIN
    UPDATE ORA_ORD.ORDER_LINE
       SET UNIT_PRICE = p_new_price
     WHERE ORDER_LINE_ID = p_order_line_id;
END;
/

CREATE OR REPLACE FUNCTION ORA_ORD.FN_ORDER_MARGIN (
    p_order_id IN NUMBER
) RETURN NUMBER IS
    v_margin NUMBER;
BEGIN
    SELECT SUM(NVL((UNIT_PRICE - (UNIT_PRICE * DISCOUNT_RATE/100)) * QUANTITY, 0))
      INTO v_margin
      FROM ORA_ORD.ORDER_LINE
     WHERE ORDER_ID = p_order_id;
    RETURN NVL(v_margin, 0);
END;
/

CREATE OR REPLACE PACKAGE ORA_ORD.PKG_ORDER_WORKFLOW AS
    PROCEDURE ADVANCE_STATUS(p_order_id NUMBER, p_status VARCHAR2);
    PROCEDURE CANCEL_ORDER(p_order_id NUMBER);
END PKG_ORDER_WORKFLOW;
/

CREATE OR REPLACE PACKAGE BODY ORA_ORD.PKG_ORDER_WORKFLOW AS
    PROCEDURE ADVANCE_STATUS(p_order_id NUMBER, p_status VARCHAR2) IS
    BEGIN
        UPDATE ORA_ORD.ORDER_FACT
           SET STATUS = p_status,
               UPDATED_AT = SYSDATE
         WHERE ORDER_ID = p_order_id;
    END;

    PROCEDURE CANCEL_ORDER(p_order_id NUMBER) IS
    BEGIN
        UPDATE ORA_ORD.ORDER_FACT
           SET STATUS = 'X',
               UPDATED_AT = SYSDATE
         WHERE ORDER_ID = p_order_id;
    END;
END PKG_ORDER_WORKFLOW;
/

CREATE OR REPLACE VIEW ORA_ORD.VW_OPEN_ORDERS AS
SELECT o.ORDER_ID,
       o.ORDER_CODE,
       o.CUSTOMER_ID,
       o.STATUS,
       o.ORDER_TOTAL,
       c.CUSTOMER_NAME
  FROM ORA_ORD.ORDER_FACT o
  JOIN ORA_CORE.CUSTOMER_DIM c ON c.CUSTOMER_ID = o.CUSTOMER_ID
 WHERE o.STATUS IN ('N','P');

PROMPT === ORA_FULFILL logistics layer ===

CREATE TABLE ORA_FULFILL.SHIPMENT_FACT (
    SHIPMENT_ID        NUMBER(12)   CONSTRAINT PK_SHIPMENT_FACT PRIMARY KEY,
    ORDER_ID           NUMBER(12)   NOT NULL,
    SERVICE_LEVEL_ID   NUMBER(6)    NOT NULL,
    STATUS             VARCHAR2(1)  DEFAULT 'N',
    SHIP_DATE          DATE,
    DELIVERY_DATE      DATE,
    CONSTRAINT FK_SHIPMENT_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES ORA_ORD.ORDER_FACT(ORDER_ID),
    CONSTRAINT FK_SHIPMENT_SERVICE FOREIGN KEY (SERVICE_LEVEL_ID)
        REFERENCES ORA_REF.SERVICE_LEVEL(SERVICE_LEVEL_ID)
);

CREATE TABLE ORA_FULFILL.SHIPMENT_EVENT (
    EVENT_ID       NUMBER(12)    CONSTRAINT PK_SHIPMENT_EVENT PRIMARY KEY,
    SHIPMENT_ID    NUMBER(12)    NOT NULL,
    EVENT_CODE     VARCHAR2(20)  NOT NULL,
    NOTES          VARCHAR2(400),
    CREATED_AT     DATE          DEFAULT SYSDATE,
    CONSTRAINT FK_EVENT_SHIPMENT FOREIGN KEY (SHIPMENT_ID)
        REFERENCES ORA_FULFILL.SHIPMENT_FACT(SHIPMENT_ID)
);

CREATE SEQUENCE ORA_FULFILL.SEQ_SHIPMENT START WITH 70000 INCREMENT BY 3;

CREATE OR REPLACE TRIGGER ORA_FULFILL.TRG_SHIPMENT_FACT_BI
BEFORE INSERT ON ORA_FULFILL.SHIPMENT_FACT
FOR EACH ROW
BEGIN
    IF :NEW.SHIPMENT_ID IS NULL THEN
        SELECT ORA_FULFILL.SEQ_SHIPMENT.NEXTVAL INTO :NEW.SHIPMENT_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE ORA_FULFILL.SP_CLOSE_SHIPMENT (
    p_shipment_id IN NUMBER
) AS
BEGIN
    UPDATE ORA_FULFILL.SHIPMENT_FACT
       SET STATUS = 'C',
           DELIVERY_DATE = NVL(DELIVERY_DATE, SYSDATE)
     WHERE SHIPMENT_ID = p_shipment_id;
END;
/

CREATE OR REPLACE VIEW ORA_FULFILL.VW_DUE_SHIPMENTS AS
SELECT s.SHIPMENT_ID,
       s.ORDER_ID,
       s.STATUS,
       s.SHIP_DATE,
       s.DELIVERY_DATE
  FROM ORA_FULFILL.SHIPMENT_FACT s
 WHERE s.STATUS <> 'C';

PROMPT === ORA_ANALYTICS reporting layer ===

CREATE OR REPLACE VIEW ORA_ANALYTICS.VW_CUSTOMER_SPEND AS
SELECT c.CUSTOMER_NAME,
       SUM(o.ORDER_TOTAL) AS TOTAL_SPEND
  FROM ORA_CORE.CUSTOMER_DIM c
  JOIN ORA_ORD.ORDER_FACT o ON o.CUSTOMER_ID = c.CUSTOMER_ID
 GROUP BY c.CUSTOMER_NAME;

CREATE OR REPLACE VIEW ORA_ANALYTICS.VW_REGION_PERF AS
SELECT r.REGION_NAME,
       COUNT(o.ORDER_ID) AS ORDER_COUNT,
       SUM(o.ORDER_MARGIN) AS TOTAL_MARGIN
  FROM ORA_REF.REGION_DIM r
  LEFT JOIN ORA_ORD.ORDER_FACT o ON o.REGION_ID = r.REGION_ID
 GROUP BY r.REGION_NAME;

CREATE OR REPLACE VIEW ORA_ANALYTICS.VW_DELIVERY_DELAY AS
SELECT f.ORDER_ID,
       f.STATUS,
       (f.DELIVERY_DATE - f.SHIP_DATE) AS DELAY_DAYS
  FROM ORA_FULFILL.SHIPMENT_FACT f
 WHERE f.DELIVERY_DATE IS NOT NULL
   AND f.SHIP_DATE IS NOT NULL;

CREATE OR REPLACE PROCEDURE ORA_ANALYTICS.SP_SNAPSHOT_FACTS AS
BEGIN
    NULL;
END;
/

PROMPT === ORA_AUDIT controls layer ===

CREATE TABLE ORA_AUDIT.AUDIT_LOG (
    AUDIT_ID      NUMBER(12)   CONSTRAINT PK_AUDIT_LOG PRIMARY KEY,
    SOURCE_SCHEMA VARCHAR2(30) NOT NULL,
    OBJECT_NAME   VARCHAR2(64) NOT NULL,
    OPERATION     VARCHAR2(20) NOT NULL,
    STATUS        VARCHAR2(1)  DEFAULT 'S',
    DETAILS       VARCHAR2(400),
    CREATED_AT    DATE         DEFAULT SYSDATE NOT NULL
);

CREATE TABLE ORA_AUDIT.JOB_RUN (
    JOB_ID          NUMBER(12) CONSTRAINT PK_JOB_RUN PRIMARY KEY,
    JOB_NAME        VARCHAR2(60) NOT NULL,
    RUN_STATUS      VARCHAR2(1)  DEFAULT 'S',
    STARTED_AT      DATE,
    COMPLETED_AT    DATE,
    ROWS_PROCESSED  NUMBER(12)
);

CREATE SEQUENCE ORA_AUDIT.SEQ_AUDIT START WITH 90000 INCREMENT BY 1;
CREATE SEQUENCE ORA_AUDIT.SEQ_JOB   START WITH 300 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ORA_AUDIT.TRG_AUDIT_LOG_BI
BEFORE INSERT ON ORA_AUDIT.AUDIT_LOG
FOR EACH ROW
BEGIN
    IF :NEW.AUDIT_ID IS NULL THEN
        SELECT ORA_AUDIT.SEQ_AUDIT.NEXTVAL INTO :NEW.AUDIT_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE ORA_AUDIT.SP_PURGE_AUDIT (
    p_days IN NUMBER
) AS
BEGIN
    DELETE FROM ORA_AUDIT.AUDIT_LOG WHERE CREATED_AT < SYSDATE - p_days;
END;
/

CREATE OR REPLACE FUNCTION ORA_AUDIT.FN_LAST_JOB_RUN (
    p_job_name IN VARCHAR2
) RETURN DATE IS
    v_run DATE;
BEGIN
    SELECT MAX(COMPLETED_AT)
      INTO v_run
      FROM ORA_AUDIT.JOB_RUN
     WHERE JOB_NAME = p_job_name;
    RETURN v_run;
END;
/

PROMPT === ORA_BILL billing layer ===

CREATE TABLE ORA_BILL.INVOICE_HEADER (
    INVOICE_ID     NUMBER(12)   CONSTRAINT PK_INVOICE_HEADER PRIMARY KEY,
    ORDER_ID       NUMBER(12)   NOT NULL,
    CUSTOMER_ID    NUMBER(10)   NOT NULL,
    STATUS         VARCHAR2(1)  DEFAULT 'N',
    INVOICE_TOTAL  NUMBER(14,2) NOT NULL,
    DUE_DATE       DATE         NOT NULL,
    PAID_DATE      DATE,
    COMMENTS       VARCHAR2(400),
    CONSTRAINT FK_INV_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES ORA_ORD.ORDER_FACT(ORDER_ID),
    CONSTRAINT FK_INV_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
        REFERENCES ORA_CORE.CUSTOMER_DIM(CUSTOMER_ID)
);

CREATE TABLE ORA_BILL.INVOICE_LINE (
    LINE_ID       NUMBER(12)  CONSTRAINT PK_INVOICE_LINE PRIMARY KEY,
    INVOICE_ID    NUMBER(12)  NOT NULL,
    LINE_NUM      NUMBER(4)   NOT NULL,
    DESCRIPTION   VARCHAR2(200) NOT NULL,
    AMOUNT        NUMBER(12,2)  NOT NULL,
    CONSTRAINT UK_INV_LINE UNIQUE (INVOICE_ID, LINE_NUM),
    CONSTRAINT FK_INV_LINE_HEADER FOREIGN KEY (INVOICE_ID)
        REFERENCES ORA_BILL.INVOICE_HEADER(INVOICE_ID)
);

CREATE SEQUENCE ORA_BILL.SEQ_INVOICE START WITH 80000 INCREMENT BY 2;

CREATE OR REPLACE TRIGGER ORA_BILL.TRG_INVOICE_HEADER_BI
BEFORE INSERT ON ORA_BILL.INVOICE_HEADER
FOR EACH ROW
BEGIN
    IF :NEW.INVOICE_ID IS NULL THEN
        SELECT ORA_BILL.SEQ_INVOICE.NEXTVAL INTO :NEW.INVOICE_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE ORA_BILL.SP_POST_INVOICE (
    p_invoice_id IN NUMBER
) AS
BEGIN
    UPDATE ORA_BILL.INVOICE_HEADER
       SET STATUS = 'P'
     WHERE INVOICE_ID = p_invoice_id;
END;
/

CREATE OR REPLACE PACKAGE ORA_BILL.PKG_BILLING_ENGINE AS
    PROCEDURE ALLOCATE_REVENUE(p_invoice_id NUMBER);
    PROCEDURE WRITE_OFF(p_invoice_id NUMBER);
END PKG_BILLING_ENGINE;
/

CREATE OR REPLACE PACKAGE BODY ORA_BILL.PKG_BILLING_ENGINE AS
    PROCEDURE ALLOCATE_REVENUE(p_invoice_id NUMBER) IS
    BEGIN
        NULL;
    END;

    PROCEDURE WRITE_OFF(p_invoice_id NUMBER) IS
    BEGIN
        UPDATE ORA_BILL.INVOICE_HEADER
           SET STATUS = 'W'
         WHERE INVOICE_ID = p_invoice_id;
    END;
END PKG_BILLING_ENGINE;
/

CREATE OR REPLACE VIEW ORA_BILL.VW_OVERDUE_INVOICE AS
SELECT i.INVOICE_ID,
       i.ORDER_ID,
       i.CUSTOMER_ID,
       i.INVOICE_TOTAL,
       i.DUE_DATE
  FROM ORA_BILL.INVOICE_HEADER i
 WHERE i.STATUS <> 'P'
   AND i.DUE_DATE < SYSDATE;

PROMPT === ORA_SEC security layer ===

CREATE TABLE ORA_SEC.USER_MATRIX (
    USER_ID       NUMBER(10)   CONSTRAINT PK_USER_MATRIX PRIMARY KEY,
    USERNAME      VARCHAR2(80) NOT NULL,
    STATUS        VARCHAR2(1)  DEFAULT 'A',
    LAST_LOGIN    DATE,
    CUSTOMER_ID   NUMBER(10),
    CONSTRAINT UK_USER_MATRIX_LOGIN UNIQUE (USERNAME)
);

CREATE TABLE ORA_SEC.ROLE_RIGHTS (
    ROLE_NAME     VARCHAR2(40) NOT NULL,
    RIGHT_CODE    VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_ROLE_RIGHTS PRIMARY KEY (ROLE_NAME, RIGHT_CODE)
);

CREATE SEQUENCE ORA_SEC.SEQ_USER START WITH 60000 INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE ORA_SEC.SP_GRANT_ROLE (
    p_user_id IN NUMBER,
    p_role    IN VARCHAR2
) AS
BEGIN
    NULL;
END;
/

CREATE OR REPLACE FUNCTION ORA_SEC.FN_IS_AUTHORIZED (
    p_user_id  IN NUMBER,
    p_right    IN VARCHAR2
) RETURN VARCHAR2 IS
BEGIN
    RETURN 'Y';
END;
/

CREATE OR REPLACE VIEW ORA_SEC.VW_ACTIVE_USERS AS
SELECT u.USER_ID,
       u.USERNAME,
       u.STATUS
  FROM ORA_SEC.USER_MATRIX u
 WHERE u.STATUS = 'A';

PROMPT === ORA_UTIL shared synonyms ===

CREATE OR REPLACE SYNONYM ORA_UTIL.SYN_CUSTOMER FOR ORA_CORE.CUSTOMER_DIM;
CREATE OR REPLACE SYNONYM ORA_UTIL.SYN_ORDER    FOR ORA_ORD.ORDER_FACT;
CREATE OR REPLACE SYNONYM ORA_UTIL.SYN_INVOICE  FOR ORA_BILL.INVOICE_HEADER;
CREATE OR REPLACE SYNONYM ORA_UTIL.SYN_REGION   FOR ORA_REF.REGION_DIM;

CREATE OR REPLACE FUNCTION ORA_UTIL.FN_CANARY RETURN VARCHAR2 IS
BEGIN
    RETURN 'ALIVE';
END;
/

CREATE OR REPLACE PACKAGE ORA_UTIL.PKG_DATA_ROUTER AS
    PROCEDURE ROUTE_CUSTOMER(p_customer_id NUMBER);
    PROCEDURE ROUTE_ORDER(p_order_id NUMBER);
END PKG_DATA_ROUTER;
/

CREATE OR REPLACE PACKAGE BODY ORA_UTIL.PKG_DATA_ROUTER AS
    PROCEDURE ROUTE_CUSTOMER(p_customer_id NUMBER) IS
    BEGIN
        NULL;
    END;

    PROCEDURE ROUTE_ORDER(p_order_id NUMBER) IS
    BEGIN
        NULL;
    END;
END PKG_DATA_ROUTER;
/

PROMPT === ORA_ML machine learning layer ===

CREATE TABLE ORA_ML.MODEL_VERSION (
    MODEL_ID        NUMBER(12)    CONSTRAINT PK_MODEL_VERSION PRIMARY KEY,
    MODEL_NAME      VARCHAR2(60)  NOT NULL,
    VERSION_LABEL   VARCHAR2(30)  NOT NULL,
    STATUS          VARCHAR2(1)   DEFAULT 'D',
    TRAINED_AT      DATE,
    CREATED_AT      DATE          DEFAULT SYSDATE
);

CREATE TABLE ORA_ML.MODEL_FEATURE (
    FEATURE_ID      NUMBER(12)   CONSTRAINT PK_MODEL_FEATURE PRIMARY KEY,
    MODEL_ID        NUMBER(12)   NOT NULL,
    FEATURE_NAME    VARCHAR2(60) NOT NULL,
    DATA_TYPE       VARCHAR2(20) NOT NULL,
    IMPORTANCE      NUMBER(5,2),
    CONSTRAINT FK_MODEL_FEATURE_VERSION FOREIGN KEY (MODEL_ID)
        REFERENCES ORA_ML.MODEL_VERSION(MODEL_ID)
);

CREATE SEQUENCE ORA_ML.SEQ_MODEL START WITH 100 INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE ORA_ML.SP_REGISTER_MODEL (
    p_model_name    IN VARCHAR2,
    p_version_label IN VARCHAR2
) AS
BEGIN
    NULL;
END;
/

CREATE OR REPLACE FUNCTION ORA_ML.FN_SCORE_MODEL (
    p_model_id IN NUMBER
) RETURN NUMBER IS
BEGIN
    RETURN p_model_id;
END;
/

CREATE OR REPLACE VIEW ORA_ML.VW_FEATURE_COVERAGE AS
SELECT m.MODEL_NAME,
       COUNT(f.FEATURE_ID) AS FEATURE_COUNT
  FROM ORA_ML.MODEL_VERSION m
  LEFT JOIN ORA_ML.MODEL_FEATURE f ON f.MODEL_ID = m.MODEL_ID
 GROUP BY m.MODEL_NAME;

PROMPT === Hydra Matrix source setup complete ===

