-- 修补缺失的 MATERIALIZED VIEW OB_ANALYTICS.MV_STATUS_COUNT (源: LAB_CORE.MV_STATUS_COUNT)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER SESSION SET CURRENT_SCHEMA = OB_ANALYTICS;

CREATE MATERIALIZED VIEW "OB_ANALYTICS"."MV_STATUS_COUNT" (
	"STATUS",
	"CNT")
REFRESH COMPLETE
 AS 
SELECT STATUS, COUNT(*) AS CNT
  FROM OB_BASE.CORE_ACCOUNT
 GROUP BY STATUS;
