
CREATE TABLE "LAB_FIN"."FIN_LEDGER" (
	"LEDGER_ID" NUMBER NOT NULL,
	"ACCOUNT_ID" NUMBER NOT NULL,
	"AMOUNT" NUMBER(12,2) NOT NULL,
	"CURRENCY" VARCHAR2(3 BYTE) DEFAULT 'CNY',
	"REMARK" VARCHAR2(100 BYTE),
	CONSTRAINT "SYS_C009782" PRIMARY KEY ("LEDGER_ID")
);

ALTER TABLE "LAB_FIN"."FIN_LEDGER" ADD CONSTRAINT "FK_LEDGER_ACCT" FOREIGN KEY ("ACCOUNT_ID") REFERENCES "LAB_CORE"."CORE_ACCOUNT" ("ACCOUNT_ID") ENABLE VALIDATE;

