-- 修补缺失的约束 FK_ORDERS_CUSTOMERS (表: OB_ANALYTICS.ORDERS_FACT)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER TABLE "OB_ANALYTICS"."ORDERS_FACT" ADD CONSTRAINT "FK_ORDERS_CUSTOMERS" FOREIGN KEY ("CUST_ID")
	  REFERENCES "OB_DATA"."CUST" ("CUST_ID") ENABLE;
