-- Gorgon's Knot - OceanBase Setup

-- Drop users if they exist to ensure a clean slate on every run
DECLARE
    PROCEDURE drop_user(p_name VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'DROP USER ' || p_name || ' CASCADE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE NOT IN (-1918, -1031) THEN -- ignore missing user or insufficient privilege
                RAISE;
            END IF;
    END;
BEGIN
    drop_user('OLYMPIAN_A');
    drop_user('OLYMPIAN_B');
    drop_user('TITAN_A');
    drop_user('TITAN_B');
    drop_user('PRIMORDIAL');
END;
/

-- Create users
CREATE USER OLYMPIAN_A IDENTIFIED BY oracle;
CREATE USER OLYMPIAN_B IDENTIFIED BY oracle;
CREATE USER TITAN_A IDENTIFIED BY oracle;
CREATE USER TITAN_B IDENTIFIED BY oracle;
CREATE USER PRIMORDIAL IDENTIFIED BY oracle;

-- Grant privileges
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM, CREATE PROCEDURE, CREATE TRIGGER TO OLYMPIAN_A;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM, CREATE PROCEDURE, CREATE TRIGGER TO OLYMPIAN_B;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM, CREATE PROCEDURE, CREATE TRIGGER TO TITAN_A;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM, CREATE PROCEDURE, CREATE TRIGGER TO TITAN_B;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM, CREATE PROCEDURE, CREATE TRIGGER TO PRIMORDIAL;

ALTER USER OLYMPIAN_A QUOTA UNLIMITED ON USERS;
ALTER USER OLYMPIAN_B QUOTA UNLIMITED ON USERS;
ALTER USER TITAN_A QUOTA UNLIMITED ON USERS;
ALTER USER TITAN_B QUOTA UNLIMITED ON USERS;
ALTER USER PRIMORDIAL QUOTA UNLIMITED ON USERS;

---------------------------------------------------
-- Schema: OLYMPIAN_A (Target for HERO_A, HERO_B)
---------------------------------------------------
CREATE TABLE OLYMPIAN_A.HEROES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    HOME_REALM VARCHAR2(50)
    -- Extra HOME_REALM column will not match source
);
CREATE SEQUENCE OLYMPIAN_A.SEQ_HERO;

-- Renamed from HERO_A.TREASURES
CREATE TABLE OLYMPIAN_A.HERO_TREASURES (
    ID NUMBER PRIMARY KEY,
    OWNER_ID NUMBER, -- Missing FK constraint
    DESCRIPTION VARCHAR2(150), -- Shorter length
    VALUE NUMBER(10, 2)
    -- Missing OWNER_ID FK, shorter DESC
);

-- Renamed from HERO_B.TREASURES
CREATE TABLE OLYMPIAN_A.LEGEND_TREASURES (
    ID NUMBER PRIMARY KEY,
    OWNER_ID NUMBER,
    DESCRIPTION VARCHAR2(200)
    -- Missing MAGIC_LEVEL column
);

-- New consolidated mission objects with trimmed structures
CREATE TABLE OLYMPIAN_A.HERO_MISSIONS (
    ID NUMBER PRIMARY KEY,
    HERO_ID NUMBER,
    NAME VARCHAR2(80),
    STATUS VARCHAR2(20) DEFAULT 'PENDING'
    -- RISK_LEVEL is missing
);
CREATE SEQUENCE OLYMPIAN_A.SEQ_MISSION;

CREATE TABLE OLYMPIAN_A.HERO_MISSION_LOG (
    ID NUMBER PRIMARY KEY,
    MISSION_ID NUMBER,
    LOG_TEXT VARCHAR2(120)
    -- Shorter log size and no FK
);
CREATE SEQUENCE OLYMPIAN_A.SEQ_MISSION_LOG;

CREATE TABLE OLYMPIAN_A.HERO_RELICS (
    ID NUMBER PRIMARY KEY,
    OWNER_ID NUMBER,
    VALUE NUMBER(8, 2)
    -- RARITY column is missing and VALUE precision differs
);

CREATE TABLE OLYMPIAN_A.HERO_TITLES (
    ID NUMBER PRIMARY KEY,
    HERO_ID NUMBER,
    TITLE VARCHAR2(80)
    -- SOURCED_FROM missing
);
CREATE SEQUENCE OLYMPIAN_A.SEQ_HERO_TITLE;

CREATE TABLE OLYMPIAN_A.LEGEND_QUESTS (
    ID NUMBER PRIMARY KEY,
    LEGEND_ID NUMBER,
    NAME VARCHAR2(80),
    STATUS VARCHAR2(20)
    -- Missing RANK column
);

CREATE TABLE OLYMPIAN_A.LEGEND_QUEST_STEPS (
    ID NUMBER PRIMARY KEY,
    QUEST_ID NUMBER,
    STEP_NAME VARCHAR2(80)
    -- COMPLETE_FLAG missing
);

CREATE TABLE OLYMPIAN_A.LEGEND_AWARDS (
    ID NUMBER PRIMARY KEY,
    LEGEND_ID NUMBER,
    AWARD VARCHAR2(80)
    -- AWARD_YEAR missing
);

CREATE TABLE OLYMPIAN_A.LEGEND_SCROLLS (
    ID NUMBER PRIMARY KEY,
    LEGEND_ID NUMBER,
    TITLE VARCHAR2(80)
    -- SECRET_CODE missing
);

CREATE TABLE OLYMPIAN_A.LEGEND_BATTLES (
    ID NUMBER PRIMARY KEY,
    LEGEND_ID NUMBER,
    OPPONENT_NAME VARCHAR2(80),
    RESULT VARCHAR2(10)
    -- RESULT is shorter than source
);
CREATE SEQUENCE OLYMPIAN_A.SEQ_LEGEND_BATTLE;

CREATE OR REPLACE VIEW OLYMPIAN_A.VW_ACTIVE_QUESTS AS
SELECT q.ID, q.NAME, COUNT(s.ID) AS STEP_COUNT
FROM OLYMPIAN_A.LEGEND_QUESTS q
LEFT JOIN OLYMPIAN_A.LEGEND_QUEST_STEPS s ON s.QUEST_ID = q.ID
GROUP BY q.ID, q.NAME;

-- LEGENDS table from HERO_B is still missing
-- PKG and procedures from HERO_B remain missing
-- VW_ALL_TREASURES is missing

-- EXTRA "noise" objects
CREATE TABLE OLYMPIAN_A.EXTRA_CLOUD_PALACE (ID NUMBER);
CREATE TABLE OLYMPIAN_A.EXTRA_PARTHENON_CACHE (ID NUMBER, NOTE VARCHAR2(50));

---------------------------------------------------
-- Schema: OLYMPIAN_B (Extraneous target schema)
---------------------------------------------------
CREATE TABLE OLYMPIAN_B.NEW_ARTIFACTS (
    ARTIFACT_ID NUMBER PRIMARY KEY,
    ARTIFACT_NAME VARCHAR2(100)
);
CREATE SEQUENCE OLYMPIAN_B.SEQ_NEW_ARTIFACT;

---------------------------------------------------
-- Schema: TITAN_A (Target for MONSTER_A data)
---------------------------------------------------
-- This table represents a split from MONSTER_A.LAIR
CREATE TABLE TITAN_A.LAIR_INFO (
    ID NUMBER PRIMARY KEY,
    LOCATION VARCHAR2(100)
    -- Missing GEAR and VICTIMS columns
);
-- EXTRA table that looks like it could be part of the split
CREATE TABLE TITAN_A.LAIR_CONTENTS (
    ID NUMBER PRIMARY KEY,
    GEAR VARCHAR2(100)
    -- Missing VICTIMS column still
);

CREATE TABLE TITAN_A.DUNGEON_INFO (
    ID NUMBER PRIMARY KEY,
    LAIR_ID NUMBER,
    DEPTH NUMBER
    -- STATUS column missing
);

CREATE TABLE TITAN_A.RAIDS (
    ID NUMBER PRIMARY KEY,
    LAIR_ID NUMBER,
    TARGET VARCHAR2(80)
    -- STATUS column missing
);

CREATE TABLE TITAN_A.SUPPLY_LINES (
    ID NUMBER PRIMARY KEY,
    LAIR_ID NUMBER,
    MATERIAL VARCHAR2(80)
    -- STOCK column missing
);

CREATE TABLE TITAN_A.WAR_CHESTS (
    ID NUMBER PRIMARY KEY,
    LAIR_ID NUMBER,
    GOLD VARCHAR2(30)
    -- GOLD stored as string and lacks constraints
);

-- MINIONS table is still MISSING
-- SEQ_MINION is MISSING
-- TRG_MINION_BI is MISSING

-- EXTRA "noise" sequence
CREATE SEQUENCE TITAN_A.SEQ_EXTRA_NOISE;

---------------------------------------------------
-- Schema: TITAN_B (Target for MONSTER_A logic)
---------------------------------------------------
CREATE TABLE TITAN_B.TRAP_STATUS (
    ID NUMBER PRIMARY KEY,
    DUNGEON_ID NUMBER,
    KIND VARCHAR2(50)
    -- IS_ARMED missing
);

CREATE TABLE TITAN_B.CURSES (
    ID NUMBER PRIMARY KEY,
    LAIR_ID NUMBER,
    TARGET_HERO VARCHAR2(80)
    -- ACTIVE_FLAG missing
);

CREATE TABLE TITAN_B.LAB_NOTES (
    ID NUMBER PRIMARY KEY,
    NOTE VARCHAR2(150)
    -- MINION context missing
);

-- VW_LAIR_RICHNESS is MISSING
-- SP_SUMMON_MINION is MISSING

CREATE OR REPLACE PACKAGE TITAN_B.PKG_MONSTER_OPS AS
  PROCEDURE SPEND_FUNDS(p_lair_id IN NUMBER, p_amount IN NUMBER, p_reason IN VARCHAR2);
END;
/
-- Body intentionally missing to exercise package difference handling

-- This synonym points to a non-existent object in this schema.
-- The actual table is in TITAN_A.
CREATE SYNONYM TITAN_B.SYN_SECRET_LAIR FOR TITAN_A.LAIR_INFO;
CREATE SYNONYM TITAN_B.SYN_FUNDS FOR TITAN_A.WAR_CHESTS;

---------------------------------------------------
-- Schema: PRIMORDIAL (Target for GOD_A)
---------------------------------------------------
-- Renamed from DOMAINS
CREATE TABLE PRIMORDIAL.REALMS (
    REALM_ID NUMBER PRIMARY KEY, -- Renamed column ID -> REALM_ID
    NAME VARCHAR2(50),
    REALM_TIER VARCHAR2(20)
);

-- PANTHEON table is present but lacks proper constraints
CREATE TABLE PRIMORDIAL.PANTHEON (
    PANTHEON_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    DOMAIN_REF NUMBER
    -- DOMAIN_REF does not enforce FK to REALMS
);

-- SEQ_DOMAIN is renamed but also points to the wrong table now
CREATE SEQUENCE PRIMORDIAL.SEQ_REALM;

CREATE TABLE PRIMORDIAL.GATES (
    GATE_ID NUMBER PRIMARY KEY,
    REALM_ID NUMBER,
    DESTINATION VARCHAR2(80)
    -- Different column names from source PORTALS
);
CREATE SEQUENCE PRIMORDIAL.SEQ_GATE;

CREATE TABLE PRIMORDIAL.COSMIC_EDICTS (
    EDICT_ID NUMBER PRIMARY KEY,
    REALM_ID NUMBER,
    TEXT VARCHAR2(120)
    -- Shorter text column
);
CREATE SEQUENCE PRIMORDIAL.SEQ_EDICT;

CREATE TABLE PRIMORDIAL.MIRACLES (
    MIRACLE_ID NUMBER PRIMARY KEY,
    PANTHEON_ID NUMBER,
    TARGET_NAME VARCHAR2(60)
    -- Shorter TARGET_NAME
);

CREATE TABLE PRIMORDIAL.RITUALS (
    RITUAL_ID NUMBER PRIMARY KEY,
    REALM_ID NUMBER,
    RITUAL_NAME VARCHAR2(100)
    -- FOCUS column missing
);

CREATE TABLE PRIMORDIAL.COSMIC_EVENTS (
    EVENT_ID NUMBER PRIMARY KEY,
    GATE_ID NUMBER,
    OMEN_TEXT VARCHAR2(150)
);

-- SP_BLESS_HERO is renamed and uses dynamic calls so it compiles even though dependencies are absent
CREATE OR REPLACE PROCEDURE PRIMORDIAL.SP_BLESS_MORTAL (p_mortal_name IN VARCHAR2) AS
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'BEGIN OLYMPIAN_A.PR_CHRONICLE_LEGEND(:1); END;' USING p_mortal_name;
    EXCEPTION
        WHEN OTHERS THEN NULL; -- dependency intentionally broken
    END;
END;
/

-- PKG_DIVINITY (renamed to PKG_COSMOS) is missing its BODY
CREATE OR REPLACE PACKAGE PRIMORDIAL.PKG_COSMOS AS
  PROCEDURE MANIFEST_POWER(p_realm_id IN NUMBER);
END;
/

-- Object types are omitted here to stay within OceanBase Oracle-mode supported syntax.
