-- 修补缺失的触发器 TRG_ORDERS_BI (表: OB_ANALYTICS.ORDERS_FACT)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE EDITIONABLE TRIGGER "OB_ANALYTICS"."TRG_ORDERS_BI" 
BEFORE INSERT ON OB_ANALYTICS.ORDERS_FACT
FOR EACH ROW
BEGIN
    IF :NEW.ORDER_ID IS NULL THEN
        SELECT SEQ_ORDERS.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL;
    END IF;
END;
ALTER TRIGGER "OB_ANALYTICS"."TRG_ORDERS_BI" ENABLE;
