-- 修补缺失的触发器 TRG_EMP_BI (表: OB_STAGE.EMP)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

CREATE OR REPLACE EDITIONABLE TRIGGER "OB_STAGE"."TRG_EMP_BI" 
BEFORE INSERT ON OB_STAGE.EMP
FOR EACH ROW
BEGIN
    IF :NEW.EMP_ID IS NULL THEN
        SELECT SEQ_EMP.NEXTVAL INTO :NEW.EMP_ID FROM DUAL;
    END IF;
END;
ALTER TRIGGER "OB_STAGE"."TRG_EMP_BI" ENABLE;
