-- 基于列差异的 ALTER TABLE 修补脚本: OB_FIN.FIN_LEDGER (源: LAB_FIN.FIN_LEDGER)
-- 本文件由校验工具自动生成，请在 OceanBase 执行前仔细审核。

ALTER SESSION SET CURRENT_SCHEMA = OB_FIN;

-- 目标端存在而源端不存在的列，以下 DROP COLUMN 为建议操作，请谨慎执行：
-- ALTER TABLE OB_FIN.FIN_LEDGER DROP COLUMN OMS_EXTRA_FLAG;
-- ALTER TABLE OB_FIN.FIN_LEDGER DROP COLUMN OMS_EXTRA_TS;
